name: Build & Push Docker

on:
  push:
    branches:
      - main  # o la rama que prefieras

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read app version
        id: app_version
        run: |
            VERSION=$(node -p "require('./package.json').version")
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t faiadolabs/k-oso-radar-backend:${{ github.sha }} .
          docker tag faiadolabs/k-oso-radar-backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/k-oso-radar-backend:latest
          docker tag faiadolabs/k-oso-radar-backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/k-oso-radar-backend:${VERSION}


      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/k-oso-radar-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/k-oso-radar-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/k-oso-radar-backend:${VERSION}
